apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: mcp-server-privileged
  annotations:
    description: "Privileged SCC for MCP server container runtime operations"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
- DAC_OVERRIDE
- SETUID
- SETGID
- SYS_CHROOT
- MKNOD
- NET_ADMIN
- SYS_PTRACE
defaultAddCapabilities:
- SYS_ADMIN
- DAC_OVERRIDE
- SETUID
- SETGID
fsGroup:
  type: RunAsAny
priority: 20
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:ai-mcp-openshift:openshift-ai-mcp-server
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- persistentVolumeClaim
- projected
- secret
